### PR TITLE
Spoilers function on wiki

### PR DESCRIPTION
**Pull request by alexanderlime**
This is an extension provided by mediawiki. The original collapse thing doesn't work properly so I added this extension.

### CODE REVIEW

**Comment by alexanderlime** [comment]
I wanna add require_once "$IP/extensions/Spoilers/Spoilers.php"; at the bottom of LocalSettings.php but I can't find the file.

**Comment by wushin** [comment]
Yeah, LocalSettings.php isn't included as it contains sensitive info.

**Comment by alexanderlime** [comment]
so can u pls help editing it? :)

**Comment by wushin** [comment]
Yeah, I can get this tested.

**Comment by wushin** [comment]
Did some testing.

Make each Pull request a new branch instead of merging into your master. It makes git act goofy when diffing multiple different changes.

I get this error when trying to run it in the master sources. This might be because debian uses an older version of mediawiki than this requires or the code is too old for the version we have.

/** * This is a backwards-compatibility shim, generated by: * https://git.wikimedia.org/blob/mediawiki%2Fcore.git/HEAD/maintenance%2FgenerateJsonI18n.php * * Beginning with MediaWiki 1.23, translation strings are stored in json files, * and the EXTENSION.i18n.php file only exists to provide compatibility with * older releases of MediaWiki. For more information about this migration, see: * https://www.mediawiki.org/wiki/Requests_for_comment/Localisation_format * * This shim maintains compatibility back to MediaWiki 1.17. *

**Comment by alexanderlime** [comment]
I used this: 
http://www.mediawiki.org/wiki/Extension:Spoilers

**Comment by wushin** [comment]
yeah, I can look into it.

**Pull request closed without merging**
