### PR TITLE
remove GTM and analytics

### PR DESCRIPTION
**Pull request by Helianthella**
This effectively removes:
- Google Analytics
- AddThis
- Bing ad conversion tracking
- Google ad conversion tracking

It greatly improves user privacy but also slightly blind us, but we don't need most of this data anyway aside for total visits and unique visitors, which can both be inferred from server-side logs. It's not like we're taking any action based on the analytics data too, and no one monitors the google analytics account AFAIK

### CODE REVIEW

**Comment by pazkero** [comment]
This effectively removes:

Google Analytics
AddThis
Bing ad conversion tracking
Google ad conversion trackingFrom the ChangeLog it seems that AddThis was kept? 🤔

**Comment by Helianthella** [comment]
AddThis is added by Google Tag Manager; removing GTM removes AddThis

**Comment by pazkero** [comment]
But we are keeping AddThis tokens?*Gotta grab his Reading Glasses in TMW to review this one*Will review later, have a test within the next 24 hours to worry about =/-- Sent from Yandex.Mail for mobile

**Comment by Helianthella** [comment]
this config option was never used because addthis was moved to GTM; will remove it though since it serves no purpose

**Comment by pazkero** [comment]
Looks good, imho. (Have not tested yet)\-- Sent from Yandex.Mail for mobile

**Pull request merged**
